 - name: Copy files 
   hosts: web1
   tasks:
    - name: copy files
      src 
      destn
   commands: 


   tasks: 
   - lineinfile:
       path: /var/www/html/index.html
       line: 'This line was added using Ansible lineinfile module!'
       create: yes


# # ---
# # - hosts: web1
# #   tasks:
# #     - name: Find files
# #       find:
# #         paths: /opt/data
# #         age: 2m
# #         size: 1m
# #         recurse: yes
# #       register: file