#Tripura kant
# Playbook.yml

---
- name : Ping Servers
  hosts :
  tasks :
  -      : 
#Ansible -m ping all

#ansible-playbook playbook.yml

# To directly run a command with running any module
# ansible -a 'cat /etc/hosts' all



#
--- 
- hosts: all
  tasks:
  - name: Create a Scheduled tasks
    cron:
      name: Run daily health report
      job: sh /opt/scripts/health.sh

      month: 2
      day: 19
      hour: 8
      minute: 10


#Simple playbook to Install httpd package
---
- hosts: web1
  tasks:
  - name: Install httpd pacakage
    yum: name=httpd state=installed


---
- hosts: web1
  tasks:
  - name: Install httpd package
    yum: name=httpd state=installed


#Download packkage using wget  install that rpm on web1 node using yum module.

---
- hosts: web1
  tasks:
  - yum:
      name: http://mirror.centos.org/centos/7/os/x86_64/Packages/wget-1.14-18.el7_6.1.x86_64.rpm
      state: present     


---
- hosts: all
  tasks:
    - name: Install unzip package
      yum:
        name: unzip-5.52
        state: present

#Install iotop package
---
- host: all
  tasks:
    - name: Install iotop package
      yum:
        name: iotop
        version: latest
        state: latest

#

#multi packages

---

- hosts: web1
  tasks:
   - yum: name=sudo state=latest
   - yum: name=vsftpd-2.2.2 state=present allow_downgrade=yes        



#copy

---
- hosts: all
  gather_facts: no
  tasks:
    - name: Copy Apache welcome file
      copy:
        src: index.html
        dest: /var/www/html/index.html
    - service:
        name: httpd
        state: reloaded

#install nginx

---
- hosts: all
  gather_facts: no
  tasks:
    - name: Install nginx
      yum:
        name: nginx
        state: present

    - name: Start and enable Nginx
      service:
        name: nginx
        state: started
        enabled: yes        

#INSTALL FIREWALLD

---
- hosts: web1
  tasks:
   - yum: name=firewalld state=installed
   - service: name=firewalld state=started



 ---
- hosts: web2
  tasks:
    - name: Install pkgs
      yum:
        name: httpd, firewalld
        state: present

    - name: Start/Enable services
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      with_items:
        - httpd
        - firewalld

    - name: Change Apache port
      replace:
        path: /etc/httpd/conf/httpd.conf
        regexp: "Listen 80"
        replace: "Listen 8082"

    - name: restart Apache
      service:
        name: httpd
        state: restarted

    - name: Add firewall rule for Apache
      firewalld:
        port: 8082/tcp
        zone: public
        permanent: yes
        state: enabled
        immediate: true  


#Create a touch file
---
- name: Create file perm.txt
  hosts: web1
  tasks:
   - name: Create file perm.txt
     file: path=/opt/data/perm.txt mode=064 state=touch



---
- name: Create file perm.txt
  hosts: web1
  tasks:
   - name: Create file perm.txt
     file: path=/opt/data/perm.txt mode=0640 state=touch


Install firewall
install httpd
configure httpd
start httpd
install mariadb
configure mariadb
start mariadb
configure firewall
configure database
Load data

install php
configure code



#####
#####
#Install firewall

sudo yum install firewalld
sudo service firewalld Start
sudo systemctl enable firewalld

#Install Mariadb
sudo yum install mariadb-server

# Configure Mariadb
sudo vi /etc/my.cnf #Configure the file with the right port

sudo service mariadb Start

sudo systemctl enable mariadb

sudo firewall-cmd --permanent --zone=public --add-port=3309/6/tcp
sudo firewall-cmd --reload



#Start Mariadb
mysql
Mariadb > Create 

#Configure Firewall


######
Install httpd
Install php
Configure Firewall
Configure httpd
start httpd
Download code
Test
###########


