#Tripura kant
# Playbook.yml

---
- name : Ping Servers
  hosts :
  tasks :
  -      : 
#Ansible -m ping all

#ansible-playbook playbook.yml

# To directly run a command with running any module
# ansible -a 'cat /etc/hosts' all



#
--- 
- hosts: all
  tasks:
  - name: Create a Scheduled tasks
    cron:
      name: Run daily health report
      job: sh /opt/scripts/health.sh

      month: 2
      day: 19
      hour: 8
      minute: 10


#Simple playbook to Install httpd package
---
- hosts: web1
  tasks:
  - name: Install httpd pacakage
    yum: name=httpd state=installed


---
- hosts: web1
  tasks:
  - name: Install httpd package
    yum: name=httpd state=installed


#Download packkage using wget  install that rpm on web1 node using yum module.

---
- hosts: web1
  tasks:
  - yum:
      name: http://mirror.centos.org/centos/7/os/x86_64/Packages/wget-1.14-18.el7_6.1.x86_64.rpm
      state: present     


---
- hosts: all
  tasks:
    - name: Install unzip package
      yum:
        name: unzip-5.52
        state: present

#Install iotop package
---
- host: all
  tasks:
    - name: Install iotop package
      yum:
        name: iotop
        version: latest
        state: latest


#multi packages

---

- hosts: web1
  tasks:
   - yum: name=sudo state=latest
   - yum: name=vsftpd-2.2.2 state=present allow_downgrade=yes        


